### ISSUE TITLE
Add command for Count

### ISSUE THREAD

**Issue by ElemontCapital** [ViNo-community/vite-node-bot#10]
Add command for Count

**Comment by JohnGarnham** [comment]
https://docs.vite.org/go-vite/api/rpc/common_models_v2.html

<html>
<body>
<h2 id="accountinfo" style="font-weight: 700; font-style: normal; font-family: Metropolis, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, &quot;Helvetica Neue&quot;, sans-serif; font-size: 2rem; vertical-align: baseline; margin: 3.75rem 0px 1.25rem; padding: 0px; box-sizing: border-box; line-height: 2.5rem; letter-spacing: -0.01em; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AccountInfo</h2>

Name | Type | Description
-- | -- | --
address | string address | Account address
blockCount | string uint64 | The total transaction number associated with the account
balanceInfoMap | map<string tokenId, BalanceInfo> | Account balance


</body>
</html>

**Comment by JohnGarnham** [comment]
Use this call https://docs.vite.org/go-vite/api/rpc/ledger_v2.html#ledger-getaccountinfobyaddress to get AccountInfo 

Call:
```
{
	"jsonrpc": "2.0",
	"id": 17,
	"method": "ledger_getAccountInfoByAddress",
	"params": ["<vite address>"]
}
```
Response (example):
```
{
    "jsonrpc": "2.0",
    "id": 17,
    "result": {
        "address": "vite_0b573f9d1fca7d830fc0d1552e3ff7b7f44455e38c8218fd10",
        "blockCount": "21846",
        "balanceInfoMap": {
            "tti_5649544520544f4b454e6e40": {
                "tokenInfo": {
                    "tokenName": "VITE",
                    "tokenSymbol": "VITE",
                    "totalSupply": "1001699224353751966255398604",
                    "decimals": 18,
                    "owner": "vite_0000000000000000000000000000000000000004d28108e76b",
                    "tokenId": "tti_5649544520544f4b454e6e40",
                    "maxSupply": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
                    "ownerBurnOnly": false,
                    "isReIssuable": true,
                    "index": 0,
                    "isOwnerBurnOnly": false
                },
                "balance": "0"
            }
        }
    }
}
```

**Comment by JohnGarnham** [comment]
Can view information with v!account [address] 

Displays block count and balances for all tokens on this address

**Comment by JohnGarnham** [comment]
v!newest vite_32c940345450196a05f5cf87bcd1a552f6be832e9c216ffee1 grabs newest account block for address and displays block count among other info

v!newest vite_32c940345450196a05f5cf87bcd1a552f6be832e9c216ffee1
Vite Node Bot
BOT
 — Today at 11:22 PM
Block Height: 154
Block Type: Response
Address: vite_32c940345450196a05f5cf87bcd1a552f6be832e9c216ffee1
To Address: vite_32c940345450196a05f5cf87bcd1a552f6be832e9c216ffee1
Token ID: tti_5649544520544f4b454e6e40
Amount: 190464481497709
Data: null
Fee: 0
Difficulty: 67108863
Nonce: bcW6IVCv2zc=
Hash: 7019a4adfbb4290151b5cc6f2b27311ba96dcb46a55eba582c2a1edae62cb0f1
Previous Hash: c87f897288c2c70d2a7d25ad69f04d7f90a54a1bf81e2f77e0df39fcb06fec11
Public Key: MauIqJJfMNWJMTb3FsKBLeo833rkNdTlZM2f2c+mUAM=
Send Block Hash: 864455aacce20a90c6914b873e1ed30f3278930f7e71a6e63bc2ef91cf364dce
Signature: 1yjrbuV2+4LaK7KSpRXv8B15AiToFEFfXRJ6ZingfgptvxEx0qaf4foSBD5JRHdt5KyzNR7v1UGuHX21uSqMDQ==
