### ISSUE TITLE
Make sure commands don't overlap with other bots

### ISSUE THREAD

**Issue by ElemontCapital** [ViNo-community/vite-node-bot#2]
Could potentially interfere with other bots on the Discord server who are using the same prefix or command names.
Solutions - use a custom prefix other bots aren't using - like !balance - or confine bot to only answer commands in its own channel.

**Comment by JohnGarnham** [comment]
Added set_prefix command but unfortunately discord.js doesn't have a nice, clean way to upgrade command prefixes like discord.py does. Will need to update config.js and possibly restart client.
